/**
 * The index.d.ts file is auto-generated by the build process.
 */
declare const appAPI: {
  ping: () => Promise<string>;
  /**
   * List available characters for a given play.net account.
   */
  sgeListCharacters: (options: {
    username: string;
    password: string;
    gameCode: string;
  }) => Promise<
    Array<{
      id: string;
      name: string;
    }>
  >;
  /**
   * Log in to game with a given character.
   */
  sgePlayCharacter: (options: {
    username: string;
    password: string;
    gameCode: string;
    characterName: string;
  }) => Promise<void>;
};
declare global {
  type TypeOfAppAPI = typeof appAPI;
  type AppAPI = {
    [K in keyof TypeOfAppAPI]: TypeOfAppAPI[K];
  };
  interface Window {
    api: AppAPI;
  }
}
export type { AppAPI };
