name: Build

on:
  # Allow developers to run this on-demand.
  workflow_dispatch:
  # Run for each commit to confirm that the build is still working.
  push:
    paths:
      - './github/workflows/build.yml'
      - 'src/**'
      - '!src/**/__tests__/**'
      - '!src/**/__mocks__/**'
      - 'resources/**'
      - 'build/**'
      - 'electron-builder.yml'
      - 'electron.vite.config.ts'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'tsconfig.web.json'

# Allow at most one instance of this workflow to run at a time.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: yarn build:mac

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: yarn build:win

      - name: Upload artifacts (linux-amd64-snap)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-linux-amd64.snap

      - name: Upload artifacts (mac-arm64-dmg)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-mac-arm64.dmg

      - name: Upload artifacts (mac-arm64-zip)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-mac-arm64.zip

      - name: Upload artifacts (mac-x64-dmg)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-mac-x64.dmg

      - name: Upload artifacts (mac-x64-zip)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-mac-x64.zip

      - name: Upload artifacts (win-x64-exe)
        uses: actions/upload-artifact@v3
        with:
          path: dist/phoenix-*-win-x64.exe
