name: Release

on:
  # Allow developers to run this on-demand.
  workflow_dispatch:
  # When merge to main branch then publish a release.
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

env:
  # Don't install husky hooks
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

        # Have to setup node twice as workaround until corepack is supported.
        # https://github.com/actions/setup-node/issues/531
      - name: Setup Node (corepack-prereq)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable corepack (yarn-prereq)
        shell: bash
        run: corepack enable

      - name: Setup Node and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List artifacts
        run: ls -R
        working-directory: dist

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release

      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ github.repository_owner }}
          SENTRY_PROJECT: ${{ github.event.repository.name }}
        with:
          environment: production
