name: Test

on:
  push:

env:
  # Don't install husky hooks
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

        # Have to setup node twice as workaround until corepack is supported.
        # https://github.com/actions/setup-node/issues/531
      - name: Setup Node (corepack-prereq)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable corepack (yarn-prereq)
        shell: bash
        run: corepack enable

      - name: Setup Node and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
